---
body:
  - attributes:
      description: 在提交之前，请执行并勾选以下所有选项以证明您已经阅读并理解了以下要求，否则该 issue 将被关闭。
      label: 验证步骤
      options:
        - label: 我已在标题简短的描述了我所遇到的问题
        - label: 我使用中文正确地描述了我所遇到的问题
        - label: 我已在 [Issues](https://github.com/xishang0128/sparkle/issues?q=is%3Aissue) 中寻找过我要提出的问题，但未找到相同的问题
        - label: 我已在 [常见问题](https://mihomo.party/docs/issues/common) 中寻找过我要提出的问题，并没有找到答案
        - label: 这是 GUI 程序的问题，而不是内核程序的问题
        - label: 我已经关闭所有杀毒软件/代理软件后测试过，问题依旧存在
        - label: 我已经使用最新的测试版本测试过，问题依旧存在
        - label: 我已经尝试过重启程序/电脑，问题依旧存在
    id: ensure
    type: checkboxes
  - attributes:
      description: 请提供操作系统类型
      label: 操作系统
      multiple: true
      options:
        - MacOS
        - Windows
        - Linux
    type: dropdown
    validations:
      required: true
  - attributes:
      description: 请提供出现问题的操作系统版本
      label: 系统版本
    type: input
    validations:
      required: true
  - attributes:
      label: 发生问题 sparkle 版本
    type: input
    validations:
      required: true
  - attributes:
      description: 请提供错误的详细描述。
      label: 描述
    type: textarea
    validations:
      required: true
  - attributes:
      description: 请提供重现错误的步骤
      label: 重现方式
    type: textarea
    validations:
      required: true
description: 提交 sparkle 漏洞
name: 错误反馈
title: '[Bug] '
