---
body:
  - attributes:
      description: 在提交之前，请执行并勾选以下所有选项以证明您已经阅读并理解了以下要求，否则该 issue 将被关闭。
      label: 验证步骤
      options:
        - label: 我已在标题简短的描述了我所需的功能
        - label: 我已在 [Issues](https://github.com/xishang0128/sparkle/issues?q=is%3Aissue) 中寻找过，但未找到我所需的功能
        - label: 这是向 GUI 程序提出的功能请求，而不是内核程序
        - label: 我未在最新的测试版本找到我所需的功能
    id: ensure
    type: checkboxes
  - attributes:
      description: 请提供操作系统类型
      label: 操作系统
      multiple: true
      options:
        - MacOS
        - Windows
        - Linux
    type: dropdown
    validations:
      required: true
  - attributes:
      description: 请提供所需功能的详细描述
      label: 描述
    type: textarea
    validations:
      required: true
description: 请求 sparkle 未实现的功能
name: 功能请求
title: '[Feature] '
