name: Sync Fork with Upstream

on:
  schedule:
    - cron: '6 9 * * *'  # Runs daily at midnight (adjust as needed)
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fork
      uses: actions/checkout@v2
      with:
        ref: V2  # Make sure you're on the V2 branch

    - name: Set Up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add Upstream Remote
      run: git remote add upstream https://github.com/xishang0128/sparkle.git

    - name: Fetch Upstream
      run: git fetch upstream

    - name: Merge Upstream into V2 Branch
      run: |
        git checkout V2  # Switch to your V2 branch
        git merge upstream/master  # Merge from upstream's master branch
        git push origin V2  # Push the changes to your fork
